
version: 2

sources:
  - name: base # this is the source_name
    database: femicide-data-project
    schema: femicide_tr_dataset

    tables:
      - name: femicide_2023
  


models:
    - name: femicide_data_check
      description: "Extracts the informant of femicide data along with historical dates and months of femicide from the femicide_2023 base table."
      columns:
          - name: informant_of_data
            description: "Femicide date"
            tests:
                - not_null